### PR TITLE
Readme typos and static files example fixes

### PR DESCRIPTION
**Pull request by tectiv3**
Found some typos and fixed handler in static files example

### CODE REVIEW

**Comment by joeybloggs** [comment]
Thanks @tectiv3!

**Comment by nkev** [comment]
I have a root folder `/static` with subfolders for `js`, `css`, etc. The code:
```Go
p.Get("/static/*", http.FileServer(http.Dir("static/")).ServeHTTP)
```
gives me a 404 in the browser even though the paths in the browser are correct (e.g. `http://localhost:5000/js/plugins/prism.js `)

Note that the code above is different to the example in the readme, which doesn't compile:
```Go
p.Get("/static/*", http.FileServer(http.Dir("static/").ServeHTTP)) 
```
Anyone able to shed light?

**Comment by joeybloggs** [comment]
Hey @nkev please open or comment in an open issue next time, hard to find this :)

ok the example is incorrect I'll update it, it should be:
```go
p.Get("/static/*", http.StripPrefix("/static/", http.FileServer(http.Dir("static"))).ServeHTTP)
```

your url needs to change though your missing the `static/` portion
```
http://localhost:5000/js/plugins/prism.js


// should be

http://localhost:5000/static/js/plugins/prism.js
```

**Comment by nkev** [comment]
Thanks for the quick response. No problem

**Pull request merged**
